"""Complete Chinese and Farsi UI dictionaries. No data or publishing I/O."""

ZH = {
    'title': '服务器资源状态', 'host': '服务器', 'cpu': '观测到的活跃核心',
    'ram': '可用 RAM', 'of': '总计', 'vram': '空闲 VRAM', 'cores': 'CPU 核心',
    'physical': '核心', 'threads': '线程', 'socket': 'CPU 插槽', 'core': '核心',
    'smt': 'SMT 线程详情', 'idle': '空闲', 'active': '活跃', 'ok': '已更新',
    'failed': '查询失败 · 当前状态未知', 'lastGood': '最近一次成功观测：',
    'unknown': '无法确认当前状态', 'stale': '观测已过期 · 当前状态未知',
    'gpuFailed': 'GPU 查询失败', 'noName': '无程序信息', 'noCores': '无逐核心观测信息',
    'sampleNote': '显示观测活动，并非调度器预留资源。',
    'jobCounter': '最近观测到的作业 ID',
    'jobCounterNote': '最近 7 天所有用户作业记录中可见的最新提交 ID，并非历史累计作业数。',
    'jobIdLimit': 'ID 循环上限', 'cumulativeReview': '',
    'gpuCount': '用于计算的 GPU', 'gpu_compute': '计算中', 'gpu_graphics': '仅图形任务',
    'gpu_idle': '无计算进程', 'gpu_unknown': '未知', 'details': '详情', 'utilization': '利用率',
    'cpuCriterion': '若样本中任一 SMT 线程的 CPU 活跃时间占比至少为 1%，该物理核心计数一次。这是观测活动，并非调度器分配量。缺少计数器或核心拓扑时显示未知。',
    'gpuCriterion': '观测到计算或 MPS 上下文的 GPU 数量；不包括桌面或仅图形会话。这不是预留资源，不完整的观测显示未知。',
    'storage': '存储空间', 'disks': '物理磁盘', 'mount': '文件系统 / 分区',
    'total': '总容量', 'used': '已用', 'available': '用户可用', 'unmounted': '未挂载',
    'container': '容器', 'swap': '交换空间', 'usage_unknown': '使用量未知',
    'storageUnknown': '存储信息不可用', 'storagePartial': '部分容量数据不可用',
    'lowSpace': '空间不足', 'fullSpace': '无用户可用空间', 'blockSize': '分区大小',
    'storageWarning': '用户可用空间低于 10%，或容量至少为 20 GB 的文件系统中可用空间不足 20 GB 时警告。用户可用容量不含预留块。',
    'readOnly': '只读', 'allocatedCpu': '已分配 Slurm CPU', 'computeNodes': '计算节点',
    'nodesAllocated': '已分配节点', 'configuredRam': '配置 RAM', 'notSampled': '无观测样本',
    'allocatedGpu': '已分配 GPU', 'allocationNote': '调度器分配量；无法获取实测 CPU 利用率。',
    'clusterNote': 'Slurm 分配量与作业名称；无逐核心实测样本。',
    'gpuClusterNote': 'Slurm 配置的 GPU；问号表示无法获取分配量、利用率或 VRAM 样本。',
    'topology': '配置的 CPU 拓扑', 'threadsPerCore': '线程/核心',
    'allocatedRam': '已分配 RAM（Slurm）', 'osFree': '操作系统空闲内存（Slurm FreeMem）',
    'notAvailable': '并非 MemAvailable', 'jobLabels': '作业名称',
    'noAssignedJobs': '无可见的已分配作业', 'visibleJobs': '可见作业',
    'jobLabelsNote': '调度器中的作业名称，并非观测到的可执行程序名称。待运行作业尚未分配节点。',
    'jobsLimit': '仅显示前 30 条；总数包含所有可见记录。',
    'state': '状态', 'nodes': '节点', 'queueFailed': '节点查询已更新；作业查询不可用',
    'fp32': '标称理论 FP32', 'combined': '合计',
    'fp32Note': 'CPU 基础频率 SIMD 与 GPU 常规运算的参考理论估算。',
    'fp32Formula': 'CPU TFLOPS = 物理核心数 × 基础 GHz × SIMD 通道数 × 每次 FMA 的 2 FLOP × 型号对应的 FMA 单元数 ÷ 1000。',
    'fp64': '标称理论 FP64',
    'precisionNote': '基于规格的理论性能：CPU 基础频率 SIMD 与 GPU 常规运算。周期性 DFT 主要参考 FP64，MLIP 主要参考 FP32。',
    'precisionFormula': 'CPU TFLOPS = 物理核心数 × 基础 GHz × SIMD 通道数 × 每次 FMA 的 2 FLOP × 型号对应的 FMA 单元数 / 1000。Silver 4116：512 位 ×1；EPYC 7002：256 位 ×2；Gold 6430：512 位 ×2。CPU 与 GPU 性能分别显示。',
    'runningJobs': '运行中作业', 'pendingJobs': '待运行作业',
    'masterScope': '通过 SG-Master 查询的整个计算集群状态；不包括主节点或登录节点。',
    'usageTitle': '实际启动作业统计',
    'usageMetric': '实际启动的唯一作业分配数量，并非 CPU 小时。每个数组任务元素仅计一次；作业步骤、batch/extern 和重新排队记录不额外计数。月份按保留记录中最早的实际启动时间划分（KST）。',
    'retainedPeriod': '当前可查询的保留记录', 'notLifetime': '仅有部分作业历史。未查询更早已清除或另行归档的记录；不保证任何月份的记录完整。',
    'retention': '配置的保留期（从作业结束计算）',
    'allUsers': '已验证全用户查询：--allusers，且控制器及数据库 PrivateData=none。',
    'scopeUnverified': '无法验证全用户查询；仅统计可见记录。',
    'approvalPending': '页面访问范围获批前，不公布姓名和排名。',
    'currentLeader': '当前运行最多', 'projectAccount': '项目 Account', 'slurmUser': '用户',
    'unassigned': '未指定 / 缺失', 'allTop5': '前 5 名 · 保留记录', 'monthTop3': '每月前 3 名 · 保留记录',
    'partialMonth': '边界月份 / 不完整', 'countJobs': '项作业',
    'noNamedAccounts': '无可查询的项目 Account 名称',
    'usageUnavailable': '作业历史查询失败 · 历史记录未知', 'audit': '验证',
    'requeuesRemoved': '已合并重新排队的重复记录', 'noStartRemoved': '已排除未实际启动的记录',
    'ambiguity': '相同 ID 存在歧义：保守下限；上限',
    'purgeCaveat': '若首次尝试记录已被清除，最早保留的启动时间并非原始启动时间。同一任务与用户的先前 NODE_FAIL、PREEMPTED 或 REQUEUED 记录作为重新排队关联依据；同一用户重复使用 ID 时需验证作业沿革。',
    'localReview': '本地审阅版 — 尚未公布身份信息，等待页面访问范围批准。',
    'lineageBounds': '若推断的重新排队关联实际为 ID 重用，则保留记录的计数范围为',
    'lastMonthTop3': '上月前 3 名', 'rankingJobs': '已启动作业数',
    'rankingScope': '按用户排名 · 仅统计保留记录，并非完整历史。',
    'methodDetails': '统计方法与覆盖范围', 'rankNumber': '排名',
    'noRetainedStarts': '无保留的已启动作业记录', 'step': '作业步骤',
    'networkVolume': '网络卷', 'unknownValue': '未知',
    'bytesNote': 'GB = 10⁹ 字节 · TB = 10¹² 字节',
    'masterStorage': 'SG-Master 存储空间',
    'masterStorageScope': 'SG-Master 挂载的文件系统；未查询计算节点的本地磁盘。',
    'sharedStorage': '共享存储', 'localStorage': 'SG-Master 本地文件系统',
    'otherStorage': '类型未知', 'localFilesystem': '本地文件系统',
    'storageObserved': '存储观测时间', 'storageStale': '存储观测已过期 · 当前容量未知',
    'storageTimeUnknown': '存储观测时间未知 · 当前容量未知',
    'storageQueryFailed': '存储查询失败 · 当前容量未知', 'usagePercent': '使用率',
    'usagePercentNote': '使用率遵循 df：100 × 已用量 ÷（已用量 + 用户可用量），向上取整。由于预留空间，总容量减去已用量可能不等于用户可用量。',
    'storageAliasesNote': '同一文件系统的多个挂载路径合并为一行，不重复累加。',
    'sharedHostScope': 'CPU、RAM 和 GPU 观测覆盖整个共享主机。研究室可使用全部 {count} 个 GPU。',
}

FA = {
    'title': 'وضعیت منابع سرور', 'host': 'سرور', 'cpu': 'هسته‌های فعال مشاهده‌شده',
    'ram': 'RAM در دسترس', 'of': 'از مجموع', 'vram': 'VRAM آزاد', 'cores': 'هسته‌های CPU',
    'physical': 'هسته', 'threads': 'رشته', 'socket': 'سوکت', 'core': 'هسته',
    'smt': 'جزئیات رشته‌های SMT', 'idle': 'بیکار', 'active': 'فعال', 'ok': 'به‌روز شد',
    'failed': 'پرس‌وجو ناموفق · وضعیت فعلی نامشخص', 'lastGood': 'آخرین مشاهدهٔ موفق:',
    'unknown': 'وضعیت فعلی قابل تأیید نیست', 'stale': 'مشاهده منقضی شده · وضعیت فعلی نامشخص',
    'gpuFailed': 'پرس‌وجوی GPU ناموفق', 'noName': 'اطلاعات برنامه موجود نیست',
    'noCores': 'اطلاعات مشاهدهٔ هر هسته موجود نیست',
    'sampleNote': 'فعالیت مشاهده‌شده نمایش داده می‌شود؛ این مقادیر رزروهای زمان‌بند نیستند.',
    'jobCounter': 'آخرین شناسهٔ کار مشاهده‌شده',
    'jobCounterNote': 'آخرین شناسهٔ ارسال قابل مشاهده در سوابق همهٔ کاربران طی 7 روز گذشته است؛ تعداد کل کارها در طول تاریخ نیست.',
    'jobIdLimit': 'حد گردش شناسه', 'cumulativeReview': '',
    'gpuCount': 'GPUهای در حال محاسبه', 'gpu_compute': 'محاسبه', 'gpu_graphics': 'فقط گرافیک',
    'gpu_idle': 'بدون فرایند محاسباتی', 'gpu_unknown': 'نامشخص', 'details': 'جزئیات',
    'utilization': 'درصد استفاده',
    'cpuCriterion': 'اگر در نمونه، زمان فعالیت CPU در دست‌کم یکی از رشته‌های SMT به 1٪ برسد، هستهٔ فیزیکی یک بار شمرده می‌شود. این فعالیت مشاهده‌شده است، نه تخصیص زمان‌بند. نبود شمارنده یا اطلاعات ساختار هسته‌ها به‌صورت نامشخص نمایش داده می‌شود.',
    'gpuCriterion': 'تعداد GPUهایی که زمینهٔ محاسباتی یا MPS در آن‌ها مشاهده شده است. نشست‌های دسکتاپ و صرفاً گرافیکی حذف می‌شوند. این مقادیر رزرو نیستند؛ مشاهدهٔ ناقص نامشخص است.',
    'storage': 'فضای ذخیره‌سازی', 'disks': 'دیسک‌های فیزیکی', 'mount': 'فایل‌سیستم / پارتیشن',
    'total': 'کل', 'used': 'مصرف‌شده', 'available': 'در دسترس کاربر',
    'unmounted': 'متصل نشده', 'container': 'کانتینر', 'swap': 'فضای مبادله',
    'usage_unknown': 'میزان مصرف نامشخص', 'storageUnknown': 'اطلاعات ذخیره‌سازی موجود نیست',
    'storagePartial': 'بعضی شمارنده‌های ظرفیت موجود نیستند', 'lowSpace': 'کمبود فضا',
    'fullSpace': 'فضای در دسترس کاربر تمام شده', 'blockSize': 'اندازهٔ پارتیشن',
    'storageWarning': 'اگر فضای در دسترس کاربر کمتر از 10٪ باشد، یا در فایل‌سیستم‌های حداقل 20 GB کمتر از 20 GB باقی بماند، هشدار داده می‌شود. فضای در دسترس کاربر بلوک‌های رزروشده را شامل نمی‌شود.',
    'readOnly': 'فقط خواندنی', 'allocatedCpu': 'CPUهای تخصیص‌یافتهٔ Slurm',
    'computeNodes': 'گره‌های محاسباتی', 'nodesAllocated': 'گره‌های دارای تخصیص',
    'configuredRam': 'RAM پیکربندی‌شده', 'notSampled': 'نمونهٔ مشاهده‌شده موجود نیست',
    'allocatedGpu': 'GPUهای تخصیص‌یافته',
    'allocationNote': 'تخصیص زمان‌بند است؛ استفادهٔ اندازه‌گیری‌شدهٔ CPU موجود نیست.',
    'clusterNote': 'تخصیص‌های Slurm و نام کارها؛ نمونهٔ اندازه‌گیری هر هسته موجود نیست.',
    'gpuClusterNote': 'GPUهای پیکربندی‌شده در Slurm؛ علامت سؤال یعنی تخصیص، میزان استفاده یا نمونهٔ VRAM موجود نیست.',
    'topology': 'ساختار پیکربندی‌شدهٔ CPU', 'threadsPerCore': 'رشته/هسته',
    'allocatedRam': 'RAM تخصیص‌یافته (Slurm)', 'osFree': 'حافظهٔ آزاد سیستم‌عامل (Slurm FreeMem)',
    'notAvailable': 'معادل MemAvailable نیست', 'jobLabels': 'نام کارها',
    'noAssignedJobs': 'کار تخصیص‌یافتهٔ قابل مشاهده‌ای نیست', 'visibleJobs': 'کارهای قابل مشاهده',
    'jobLabelsNote': 'نام کارها در زمان‌بند است، نه نام فایل اجرایی مشاهده‌شده. کارهای در انتظار هنوز گرهٔ تخصیص‌یافته ندارند.',
    'jobsLimit': '30 مورد نخست نمایش داده می‌شوند؛ مجموع شامل همهٔ رکوردهای قابل مشاهده است.',
    'state': 'وضعیت', 'nodes': 'گره‌ها',
    'queueFailed': 'پرس‌وجوی گره‌ها به‌روز شد؛ پرس‌وجوی کارها موجود نیست',
    'fp32': 'FP32 نظری اسمی', 'combined': 'مجموع',
    'fp32Note': 'برآورد مرجع نظری بر پایهٔ SIMD با فرکانس پایهٔ CPU و محاسبات معمول GPU.',
    'fp32Formula': 'CPU TFLOPS = تعداد هسته‌های فیزیکی × فرکانس پایه به GHz × تعداد مسیرهای SIMD × 2 FLOP در هر FMA × تعداد واحدهای FMA ویژهٔ مدل ÷ 1000.',
    'fp64': 'FP64 نظری اسمی',
    'precisionNote': 'نرخ نظری بر پایهٔ مشخصات: SIMD در فرکانس پایهٔ CPU و محاسبات معمول GPU. FP64 برای DFT تناوبی و FP32 برای محاسبات MLIP شاخص اصلی است.',
    'precisionFormula': 'CPU TFLOPS = تعداد هسته‌های فیزیکی × فرکانس پایه به GHz × تعداد مسیرهای SIMD × 2 FLOP در هر FMA × تعداد واحدهای FMA ویژهٔ مدل / 1000. Silver 4116: 512 بیت ×1؛ EPYC 7002: 256 بیت ×2؛ Gold 6430: 512 بیت ×2. نرخ CPU و GPU جداگانه نمایش داده می‌شود.',
    'runningJobs': 'کارهای در حال اجرا', 'pendingJobs': 'کارهای در انتظار',
    'masterScope': 'وضعیت کل خوشهٔ محاسباتی از طریق SG-Master پرس‌وجو شده است؛ میزبان اصلی و میزبان ورود شامل نمی‌شوند.',
    'usageTitle': 'شمارش کارهای واقعاً آغازشده',
    'usageMetric': 'تعداد تخصیص‌های یکتای واقعاً آغازشده است، نه ساعت CPU. هر عنصر آرایه یک بار شمرده می‌شود؛ مراحل کار، batch/extern و صف‌بندی مجدد کار اضافی محسوب نمی‌شوند. ماه بر اساس نخستین زمان آغاز واقعی در سوابق باقی‌مانده و به وقت کره (KST) تعیین می‌شود.',
    'retainedPeriod': 'سوابق باقی‌ماندهٔ قابل پرس‌وجو',
    'notLifetime': 'تاریخچهٔ کارها ناقص است. سوابق قدیمی‌ترِ حذف‌شده یا جداگانه بایگانی‌شده بازیابی نشده‌اند؛ کامل بودن هیچ ماهی تضمین نمی‌شود.',
    'retention': 'مدت نگهداری پیکربندی‌شده (از پایان کار)',
    'allUsers': 'دسترسی به همهٔ کاربران تأیید شده: --allusers و PrivateData=none در کنترل‌گر و پایگاه داده.',
    'scopeUnverified': 'دسترسی به همهٔ کاربران تأیید نشده؛ فقط سوابق قابل مشاهده نمایش داده می‌شوند.',
    'approvalPending': 'تا تأیید محدودهٔ دسترسی صفحه، نام‌ها و رتبه‌ها منتشر نمی‌شوند.',
    'currentLeader': 'بیشترین کار در حال اجرا', 'projectAccount': 'Account پروژه',
    'slurmUser': 'کاربر', 'unassigned': 'تعیین‌نشده / مفقود',
    'allTop5': '5 نفر برتر · سوابق باقی‌مانده', 'monthTop3': '3 نفر برتر هر ماه · سوابق باقی‌مانده',
    'partialMonth': 'ماه مرزی / ناقص', 'countJobs': 'کار',
    'noNamedAccounts': 'نام Account پروژهٔ قابل مشاهده‌ای نیست',
    'usageUnavailable': 'پرس‌وجوی سوابق کار ناموفق · تاریخچه نامشخص', 'audit': 'اعتبارسنجی',
    'requeuesRemoved': 'رکوردهای تکراری صف‌بندی مجدد ادغام شدند',
    'noStartRemoved': 'رکوردهای بدون آغاز واقعی حذف شدند',
    'ambiguity': 'ابهام شناسهٔ یکسان: شمارش محافظه‌کارانهٔ حد پایین؛ حد بالا',
    'purgeCaveat': 'اگر نخستین تلاش حذف شده باشد، نخستین زمان آغاز باقی‌مانده با زمان آغاز اصلی متفاوت است. رکوردهای قبلی NODE_FAIL، PREEMPTED یا REQUEUED برای همان کار و کاربر، مبنای ارتباط صف‌بندی مجدد هستند. استفادهٔ مجدد همان کاربر از یک شناسه نیازمند اعتبارسنجی تبار کار است.',
    'localReview': 'نسخهٔ بازبینی محلی — هویت‌ها منتشر نشده‌اند؛ تأیید محدودهٔ دسترسی صفحه در انتظار است.',
    'lineageBounds': 'دامنهٔ شمارش سوابق باقی‌مانده، اگر ارتباط‌های استنباط‌شدهٔ صف‌بندی مجدد در واقع استفادهٔ مجدد شناسه باشند',
    'lastMonthTop3': '3 نفر برتر ماه گذشته', 'rankingJobs': 'کارهای آغازشده',
    'rankingScope': 'رتبه‌بندی کاربران · فقط سوابق باقی‌مانده، نه کل تاریخچه.',
    'methodDetails': 'روش شمارش و پوشش سوابق', 'rankNumber': 'رتبه',
    'noRetainedStarts': 'سابقهٔ باقی‌مانده‌ای از کارهای آغازشده نیست',
    'step': 'مرحلهٔ کار', 'networkVolume': 'فضای ذخیره‌سازی شبکه', 'unknownValue': 'نامشخص',
    'bytesNote': 'GB = 10⁹ بایت · TB = 10¹² بایت',
    'masterStorage': 'فضای ذخیره‌سازی SG-Master',
    'masterStorageScope': 'فایل‌سیستم‌های متصل به SG-Master؛ دیسک‌های محلی گره‌های محاسباتی پرس‌وجو نشده‌اند.',
    'sharedStorage': 'ذخیره‌سازی مشترک', 'localStorage': 'فایل‌سیستم‌های محلی SG-Master',
    'otherStorage': 'نوع نامشخص', 'localFilesystem': 'فایل‌سیستم محلی',
    'storageObserved': 'زمان مشاهدهٔ ذخیره‌سازی',
    'storageStale': 'مشاهدهٔ ذخیره‌سازی منقضی شده · ظرفیت فعلی نامشخص',
    'storageTimeUnknown': 'زمان مشاهدهٔ ذخیره‌سازی نامشخص · ظرفیت فعلی نامشخص',
    'storageQueryFailed': 'پرس‌وجوی ذخیره‌سازی ناموفق · ظرفیت فعلی نامشخص',
    'usagePercent': 'درصد مصرف',
    'usagePercentNote': 'درصد مصرف مطابق df است: 100 × مصرف‌شده ÷ (مصرف‌شده + در دسترس کاربر)، با گرد کردن رو به بالا. به‌دلیل فضای رزروشده، اختلاف کل و مصرف‌شده ممکن است با فضای در دسترس کاربر برابر نباشد.',
    'storageAliasesNote': 'مسیرهای اتصال یک فایل‌سیستم در یک سطر نمایش داده می‌شوند و دوباره جمع نمی‌شوند.',
    'sharedHostScope': 'مشاهدات CPU، RAM و GPU کل میزبان مشترک را پوشش می‌دهند. آزمایشگاه می‌تواند از تمام {count} GPU استفاده کند.',
}

STATES_ZH = {
    'RUNNING': '运行中', 'PENDING': '待运行', 'COMPLETING': '结束处理中', 'COMPLETED': '已完成',
    'CONFIGURING': '配置中', 'CANCELLED': '已取消', 'FAILED': '失败', 'TIMEOUT': '超时',
    'SUSPENDED': '已暂停', 'NODE_FAIL': '节点故障', 'PREEMPTED': '已被抢占', 'REQUEUED': '重新排队',
    'OUT_OF_MEMORY': '内存不足', 'BOOT_FAIL': '启动失败', 'DEADLINE': '超过截止时间',
    'REQUEUE_FED': '联邦重新排队', 'REQUEUE_HOLD': '重新排队并暂停', 'RESIZING': '调整规模中',
    'REVOKED': '已撤销', 'SIGNALING': '发送信号中', 'SPECIAL_EXIT': '特殊退出',
    'STAGE_OUT': '输出传输中', 'STOPPED': '已停止', 'IDLE': '空闲', 'ALLOCATED': '已分配',
    'MIXED': '部分分配', 'DOWN': '停用', 'DRAIN': '停止分配', 'DRAINED': '停止分配',
    'DRAINING': '等待作业结束', 'FAIL': '故障', 'FAILING': '故障处理中', 'FUTURE': '未来启用',
    'UNKNOWN': '未知', 'MAINT': '维护中', 'RESERVED': '已预留', 'PERFCTRS': '性能计数器使用中',
    'PLANNED': '已计划', 'INVALID_REG': '注册信息无效', 'NOT_RESPONDING': '无响应',
    'POWER_DOWN': '等待关机', 'POWERED_DOWN': '已关机', 'POWERING_DOWN': '关机中',
    'POWER_UP': '等待开机', 'POWERING_UP': '开机中', 'REBOOT_REQUESTED': '已请求重启',
    'REBOOT_ISSUED': '重启中',
}

STATES_FA = {
    'RUNNING': 'در حال اجرا', 'PENDING': 'در انتظار', 'COMPLETING': 'در حال پایان',
    'COMPLETED': 'پایان‌یافته', 'CONFIGURING': 'در حال پیکربندی', 'CANCELLED': 'لغوشده',
    'FAILED': 'ناموفق', 'TIMEOUT': 'پایان مهلت اجرا', 'SUSPENDED': 'معلق',
    'NODE_FAIL': 'خرابی گره', 'PREEMPTED': 'متوقف‌شده با حق تقدم', 'REQUEUED': 'صف‌بندی مجدد',
    'OUT_OF_MEMORY': 'کمبود حافظه', 'BOOT_FAIL': 'راه‌اندازی ناموفق', 'DEADLINE': 'گذشتن از مهلت',
    'REQUEUE_FED': 'صف‌بندی مجدد فدراسیونی', 'REQUEUE_HOLD': 'صف‌بندی مجدد و تعلیق',
    'RESIZING': 'در حال تغییر اندازه', 'REVOKED': 'پس‌گرفته‌شده', 'SIGNALING': 'در حال ارسال سیگنال',
    'SPECIAL_EXIT': 'خروج ویژه', 'STAGE_OUT': 'در حال انتقال خروجی', 'STOPPED': 'متوقف',
    'IDLE': 'بیکار', 'ALLOCATED': 'تخصیص‌یافته', 'MIXED': 'تخصیص جزئی', 'DOWN': 'خارج از سرویس',
    'DRAIN': 'تخصیص متوقف', 'DRAINED': 'تخصیص متوقف', 'DRAINING': 'در انتظار پایان کارها',
    'FAIL': 'خرابی', 'FAILING': 'در حال رسیدگی به خرابی', 'FUTURE': 'استفادهٔ آتی',
    'UNKNOWN': 'نامشخص', 'MAINT': 'تعمیر و نگهداری', 'RESERVED': 'رزروشده',
    'PERFCTRS': 'شمارنده‌های عملکرد در حال استفاده', 'PLANNED': 'برنامه‌ریزی‌شده',
    'INVALID_REG': 'ثبت نامعتبر', 'NOT_RESPONDING': 'بدون پاسخ',
    'POWER_DOWN': 'در انتظار خاموشی', 'POWERED_DOWN': 'خاموش', 'POWERING_DOWN': 'در حال خاموشی',
    'POWER_UP': 'در انتظار روشن شدن', 'POWERING_UP': 'در حال روشن شدن',
    'REBOOT_REQUESTED': 'درخواست راه‌اندازی مجدد', 'REBOOT_ISSUED': 'در حال راه‌اندازی مجدد',
}

RETENTION_UNITS = {
    'ko': dict(second='초', minute='분', hour='시간', day='일', week='주', month='개월', year='년'),
    'zh': dict(second='秒', minute='分钟', hour='小时', day='天', week='周', month='个月', year='年'),
    'fa': dict(second='ثانیه', minute='دقیقه', hour='ساعت', day='روز', week='هفته', month='ماه', year='سال'),
}

RTL_CSS = """
.tabs{flex-wrap:wrap}.status::before{margin-right:0;margin-inline-end:7px}
.unit,.gpu-util small{margin-left:0;margin-inline-start:5px}.swatch{margin-right:0;margin-inline-end:3px}
.node,.job-details th,.job-details td,.master-storage-table caption{text-align:start}
.tab,.node-name,.gpu-name,.node-jobs,.gpu-program,.thread-name,.core-program{unicode-bidi:plaintext}
.value,.gpu-count,.node-count,.gpu-bottom b,.thread-use,.core-id,.core-util{direction:ltr;unicode-bidi:isolate}
.storage td:not(:first-child){direction:ltr;unicode-bidi:isolate}
.mount-alias{direction:ltr;unicode-bidi:isolate}
[dir=rtl] .storage th:first-child,[dir=rtl] .storage td:first-child{text-align:right}
[dir=rtl] .mount-alias{text-align:right}
[dir=rtl] body{line-height:1.7}
"""
