#!/usr/bin/env python3
"""Create the homepage's 1200 x 630 scientific sharing image.

Requires Python 3.10+, Pillow, and the repository's Node.js runtime (>=20).
The Cu-BTC view is generated by the existing MofRenderer.project() function,
with all eight catalog entries assigned to MOF_MODELS. Thus the atom radii,
colors, periodic cells, [001] view, and common physical scale remain those of
the interactive viewer. No CIF or renderer is modified.

Usage: python scripts/generate-homepage-social.py [--check]
Optional --node, --font-regular, and --font-bold arguments select runtimes and
fonts. Defaults use Arial on Windows or DejaVu Sans on Linux/macOS; Pillow's
bundled default is the final portable fallback. To reproduce identical PNG
bytes across platforms, supply identical TrueType font files and use the
same Pillow version. --check verifies the checked-in PNG against regeneration.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
from pathlib import Path
import subprocess

from PIL import Image, ImageDraw, ImageFont, PngImagePlugin


REPOSITORY = Path(__file__).resolve().parents[1]
IMAGE_SIZE = (1200, 630)
PLOT_ORIGIN = (550, 64)
PLOT_SIZE = (610, 500)
SUPERSAMPLE = 3
BACKGROUND = "#f5f4f2"
TITLE = "Chung Research Group @ PNU"
TAGLINE = "Materials · Computation · Intelligence"
DOMAIN = "chung-research-group.github.io"


def font_path(explicit: str | None, bold: bool) -> str | None:
    if explicit:
        path = Path(explicit).expanduser().resolve()
        if not path.is_file():
            raise FileNotFoundError(f"Font does not exist: {path}")
        return str(path)
    filename = "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"
    candidates = [
        Path("C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf"),
        Path("/usr/share/fonts/truetype/dejavu") / filename,
        Path("/Library/Fonts/Arial Bold.ttf" if bold else "/Library/Fonts/Arial.ttf"),
    ]
    for path in candidates:
        if path.is_file():
            return str(path)
    try:
        return ImageFont.truetype(filename, 20).path
    except OSError:
        return None


def rgba(color: str, alpha: float = 1.0) -> tuple[int, int, int, int]:
    color = color.lstrip("#")
    return (*[int(color[i:i + 2], 16) for i in (0, 2, 4)], round(alpha * 255))


def project(node: str) -> dict:
    javascript = r"""
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const root = process.argv[1], width = Number(process.argv[2]), height = Number(process.argv[3]);
const models = JSON.parse(fs.readFileSync(path.join(root, 'data/mof-catalog.json'), 'utf8'));
if (models.length !== 8) throw new Error('Expected all eight catalog entries for the common scale.');
const sandbox = { MOF_MODELS: models };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root, 'assets/mof-renderer.js'), 'utf8'), sandbox);
const model = models.find(model => model.slug === 'cu-btc');
const scene = sandbox.MofRenderer.geometry(model);
if (scene.repetitions.join(',') !== '2,2,1') throw new Error('Expected Cu-BTC 2 x 2 x 1 PBC cells.');
if (scene.viewDirection !== '[001]') throw new Error('Expected the initial front pore view.');
const shapes = sandbox.MofRenderer.project(model, width, height, { quaternion: [1, 0, 0, 0], zoom: 1 });
if (shapes.some(shape => !['atom', 'bond', 'cell'].includes(shape.kind))) throw new Error('Unexpected labels or shapes.');
process.stdout.write(JSON.stringify({ shapes, model: model.name, repetitions: scene.repetitions,
  direction: scene.viewDirection, pixelsPerAngstrom: sandbox.MofRenderer.viewScale(model, width, height),
  catalogModels: models.length }));
"""
    completed = subprocess.run(
        [node, "-e", javascript, str(REPOSITORY), *map(str, PLOT_SIZE)],
        check=True, capture_output=True, text=True,
    )
    return json.loads(completed.stdout)


def render(projection: dict, regular_path: str | None, bold_path: str | None) -> bytes:
    s = SUPERSAMPLE
    image = Image.new("RGB", tuple(n * s for n in IMAGE_SIZE), BACKGROUND)
    draw = ImageDraw.Draw(image, "RGBA")

    def font(size: int, bold: bool = False):
        path = bold_path if bold else regular_path
        return ImageFont.truetype(path, size * s) if path else ImageFont.load_default(size=size * s)

    def text(x: float, y: float, value: str, size: int, color: str, bold: bool = False):
        draw.text((x * s, y * s), value, font=font(size, bold), fill=rgba(color), anchor="lt")

    def line(a, b, color, width, dashed=False):
        scaled_a = tuple(v * s for v in a)
        scaled_b = tuple(v * s for v in b)
        stroke = max(1, round(width * s))
        if not dashed:
            draw.line((*scaled_a, *scaled_b), fill=color, width=stroke)
            radius = stroke / 2
            for x, y in (scaled_a, scaled_b):
                draw.ellipse((x - radius, y - radius, x + radius, y + radius), fill=color)
            return
        dx, dy = b[0] - a[0], b[1] - a[1]
        length = math.hypot(dx, dy)
        if length == 0:
            return
        for start in range(0, math.ceil(length), 7):
            end = min(start + 3, length)
            p = (a[0] + dx * start / length, a[1] + dy * start / length)
            q = (a[0] + dx * end / length, a[1] + dy * end / length)
            line(p, q, color, width)

    draw.rectangle((0, 0, IMAGE_SIZE[0] * s, 7 * s), fill=rgba("#005baa"))
    draw.line((524 * s, 88 * s, 524 * s, 534 * s), fill=rgba("#d6dfe6"), width=s)
    text(56, 104, "PUSAN NATIONAL UNIVERSITY", 15, "#52718d", True)
    text(56, 172, "Chung Research", 46, "#172b3a", True)
    text(56, 230, "Group @ PNU", 46, "#172b3a", True)
    text(58, 326, TAGLINE, 21, "#005baa")
    text(58, 564, DOMAIN, 21, "#526575")

    ox, oy = PLOT_ORIGIN
    for shape in projection["shapes"]:
        x, y = shape["x"] + ox, shape["y"] + oy
        if shape["kind"] in ("cell", "bond"):
            line((x, y), (shape["x2"] + ox, shape["y2"] + oy),
                 rgba(shape["color"], shape.get("alpha", 1)), shape["width"], shape.get("dashed", False))
        else:
            radius = shape["r"]
            draw.ellipse(((x - radius) * s, (y - radius) * s,
                          (x + radius) * s, (y + radius) * s), fill=rgba(shape["color"]))
            hx, hy, hr = x - radius * .25, y - radius * .3, radius * .33
            draw.ellipse(((hx - hr) * s, (hy - hr) * s,
                          (hx + hr) * s, (hy + hr) * s), fill=(255, 255, 255, 115))
    # This is a model caption, never a crystallographic axis annotation.
    text(804, 580, "Cu-BTC", 20, "#526575")

    image = image.resize(IMAGE_SIZE, Image.Resampling.LANCZOS)
    info = PngImagePlugin.PngInfo()
    info.add_text("Title", TITLE)
    info.add_text("Description", f"{TAGLINE}. Cu-BTC CIF-derived 2 x 2 x 1 periodic cells, [001] view; hydrogen omitted.")
    info.add_text("Source", DOMAIN)
    info.add_text("CatalogSHA256", hashlib.sha256((REPOSITORY / "data/mof-catalog.json").read_bytes()).hexdigest())
    info.add_text("RendererSHA256", hashlib.sha256((REPOSITORY / "assets/mof-renderer.js").read_bytes()).hexdigest())
    output = io.BytesIO()
    image.save(output, format="PNG", optimize=True, pnginfo=info)
    return output.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--node", default="node", help="Node.js executable (default: node)")
    parser.add_argument("--font-regular", help="Regular TrueType font file")
    parser.add_argument("--font-bold", help="Bold TrueType font file")
    parser.add_argument("--check", action="store_true", help="Verify the existing PNG without writing")
    args = parser.parse_args()
    regular, bold = font_path(args.font_regular, False), font_path(args.font_bold, True)
    projection = project(args.node)
    png = render(projection, regular, bold)
    path = REPOSITORY / "images/homepage-social.png"
    if args.check:
        if not path.is_file() or path.read_bytes() != png:
            raise SystemExit("Homepage sharing image does not match regeneration.")
    else:
        path.write_bytes(png)
    with Image.open(io.BytesIO(png)) as image:
        assert image.size == IMAGE_SIZE and image.format == "PNG"
    print(json.dumps({"path": str(path), "size": list(IMAGE_SIZE), "bytes": len(png),
                      "sha256": hashlib.sha256(png).hexdigest(), "checked": args.check,
                      "fonts": {"regular": regular or "Pillow default", "bold": bold or "Pillow default"},
                      "geometry": {key: value for key, value in projection.items() if key != "shapes"},
                      "shapeCount": len(projection["shapes"])}, ensure_ascii=False))


if __name__ == "__main__":
    main()
